baseURL = "https://ziyi-yan.github.io/"
languageCode = "zh-cn"
title = "Ziyi Yan | 严子怡"

theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "日志"
    url = "/posts"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    #description = "An Explorer"
    footer = "&copy; [Ziyi Yan](https://ziyi-yan.github.io) 2018 - 2019 | [GitHub](https://github.com/ziyi-yan) | [Twitter](https://twitter.com/ZiyiYan23) | [LinkedIn](https://linkedin.com/in/ziyi-yan)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
